#!/bin/bash

echo '======== Process list ========'
ps ax | grep -e 'node'
echo '======== Forever list ======== Kill with: forever stop #PID'
forever list
echo '======== Tail bozoid.log ========'
tail -f /root/.forever/bozoid.frv
